const dotenv = require("dotenv");
dotenv.config();

// APP
const PORT = process.env.PORT;
const JWT_SECRET = process.env.JWT_SECRET;

// DATABASE
const DATABASE_URL = process.env.DATABASE_URL;

// AUTH-PASSWORD
const PASSWORD_MINIMUM_LENGTH = process.env.PASSWORD_MINIMUM_LENGTH;
const PASSWORD_MAXIMUM_LENGTH = process.env.PASSWORD_MAXIMUM_LENGTH;

// AUTH-USERNAME
const USERNAME_MINIMUM_LENGTH = process.env.USERNAME_MINIMUM_LENGTH;
const USERNAME_MAXIMUM_LENGTH = process.env.USERNAME_MAXIMUM_LENGTH;

// AUTH-NAME
const NAME_MAXIMUM_LENGTH = process.env.NAME_MAXIMUM_LENGTH;

// NOTE-TITLE
const NOTE_TITLE_MINIMUM_LENGTH = process.env.NOTE_TITLE_MINIMUM_LENGTH;
const NOTE_TITLE_MAXIMUM_LENGTH = process.env.NOTE_TITLE_MAXIMUM_LENGTH;

// NOTE-DESCRIPTION
const NOTE_DESCRIPTION_MINIMUM_LENGTH = process.env.NOTE_DESCRIPTION_MINIMUM_LENGTH;
const NOTE_DESCRIPTION_MAXIMUM_LENGTH = process.env.NOTE_DESCRIPTION_MAXIMUM_LENGTH;

module.exports = {
  NOTE_DESCRIPTION_MINIMUM_LENGTH,
  NOTE_DESCRIPTION_MAXIMUM_LENGTH,
  NOTE_TITLE_MINIMUM_LENGTH,
  NOTE_TITLE_MAXIMUM_LENGTH,
  PASSWORD_MINIMUM_LENGTH,
  PASSWORD_MAXIMUM_LENGTH,
  USERNAME_MINIMUM_LENGTH,
  USERNAME_MAXIMUM_LENGTH,
  NAME_MAXIMUM_LENGTH,
  DATABASE_URL,
  JWT_SECRET,
  PORT,
};
